const fs=require('fs');
const assert=require('assert');
const s=fs.readFileSync('index.html','utf8');
const p=fs.readFileSync('play.html','utf8');
function has(x,msg){assert(s.includes(x),msg||x)}
has("conan:{},ayanokouji",'sprite registration');
has("conan:'#4B8BFF'",'color registration');
has('conan:HP_STD','shared HP registration');
has('const CONAN={','constants');
has('clueMax:4','four clues');
has('basicDmg:18, basicCd:gs(.9)','basic values');
has('kickDmg:85, kickCd:gs(7), kickWind:gs(.6)','kick values');
has('needleDmg:5, needleCd:gs(10)','needle values');
has('drowsyT:gs(.8), sleepT:gs(2.5), wakeDmg:60, groggyT:gs(2)','sleep chain');
has('skateCd:gs(9), skateT:gs(1.8), skateMove:2.5, skateTake:.50','skate values');
has('ultDmg:140, ultCd:gs(12), ultWind:gs(1.2)','ultimate values');
has("name:'Conan Edogawa'",'roster entry');
has("tag:'Strategist · Controller · Ranged – Analysis – Precision'",'role');
has("Locked – Gather 4 Clues",'locked text');
has("Case Solved – One Truth Prevails ready",'case solved text');
has('function conanAddClue','clue engine');
has('function conanWatchSkills','active-skill observation');
has('function conanSleepDamage','60 damage wake');
has('function conanSkateMiss','skate miss clue');
has('function conanSolvedTarget','ultimate target priority');
has("o.conanWeak=CONAN.weakT; o.conanWeakBy=f",'weakness exposed');
has("if(t.key==='conan'&&!t.swapAs&&t.conanSkate) amt*=CONAN.skateTake",'skate defense');
has("if(src&&src.conanWeak>0) acc*=CONAN.weakAcc",'weakness accuracy');
has('CONAN EDOGAWA WINS!','victory text');
assert(!/const CONAN=\{[^}]*maxHp/s.test(s),'CONAN must not hard-code Maximum HP');
assert(p.includes("name:'Conan Edogawa'"),'play build contains Conan');
assert(p.includes('function conanAddClue'),'play build contains Conan engine');
console.log('Conan contract: PASS');
