const fs=require('fs');
const assert=require('assert');
const s=fs.readFileSync('index.html','utf8');
const p=fs.readFileSync('play.html','utf8');
function has(x,msg){assert(s.includes(x),msg||x)}
function lacks(x,msg){assert(!s.includes(x),msg||('unexpected: '+x))}
has("conan:{},ayanokouji",'sprite registration');
has("conan:'#4B8BFF'",'color registration');
has('conan:HP_STD','shared HP registration');
has('clueMax:5','five clues');
has('basicDmg:6, basicCd:gs(1.6), basicWind:gs(.55), basicRange:360','slow basic');
has('kickDmg:85, kickCd:gs(15), kickWind:gs(.6), kickSpeed:540, kickStun:gs(3), kickKb:1300','15s football / 3s stun / 35% knockback tuning');
has('needleDmg:2, needleCd:gs(12)','lower wristwatch damage');
has('skateCd:gs(10), skateT:gs(1.8), skateMove:2.5, skateTake:.50, skateDmg:18','lower skateboard damage');
has('ultDmg:38, ultCd:gs(.5), ultWind:gs(.7), ultStun:gs(1.5)','decisive evidence values');
has("name:'Conan Edogawa'",'roster entry');
has('<b>Basic · Deduction</b>','basic is deduction');
has('This is Conan\'s only football attack','only football skill copy');
has('Locked – Gather ${CONAN.clueMax} Clues','five clue lock');
has('Case Solved – Decisive Evidence ready','case solved gauge');
has("function conanOnBasicHit(f,t){\n  conanAddClue(f,t,'DEDUCTION');",'one basic hit = one clue');
has("hurt(t,CONAN.basicDmg,f,false,'conanDeduction')",'basic direct hit');
has("hurt(t,CONAN.ultDmg,f,'DECISIVE EVIDENCE','conanEvidence')",'evidence direct hit');
has('stunFx(t,CONAN.ultStun','evidence stun');
lacks('function conanWatchSkills','skill observation no longer grants clues');
lacks('function conanSkateMiss','skate misses no longer grant clues');
lacks("conanAddClue(f,o,'STUN-GUN WRISTWATCH')",'wristwatch no clue');
lacks("conanShot(f,'basic'",'basic is not a football projectile');
lacks('function conanUltimateShot','ultimate is not a football bank shot');
lacks('conanWeak','Weakness Exposed removed for lower damage');
has("pw:{dmg:42,dur:46,mob:82,as:48,rng:74,cc:92,uti:90,con:72,cmb:20}",'power chart rebalance');
has('CONAN EDOGAWA WINS!','victory text');
assert(!/const CONAN=\{[^}]*maxHp/s.test(s),'CONAN must not hard-code Maximum HP');
assert(p.includes("name:'Conan Edogawa'"),'play build contains Conan');
assert(p.includes("kickCd:gs(15)"),'play build contains 15s football');
console.log('Conan rebalance contract: PASS');
