const fs=require('fs');
const assert=require('assert');
const s=fs.readFileSync('index.html','utf8');
const p=fs.readFileSync('play.html','utf8');
function has(x,msg){assert(s.includes(x),msg||x)}
has("conan:{},ayanokouji",'sprite registration');
has("conan:'#4B8BFF'",'color registration');
has('conan:HP_STD','shared HP registration');
has('const CONAN={','constants');
has('clueMax:4','four clues');
has('basicDmg:18, basicCd:gs(.9)','basic values');
has('kickDmg:85, kickCd:gs(7), kickWind:gs(.6)','kick values');
has('needleDmg:5, needleCd:gs(10)','needle values');
has('drowsyT:gs(.8), sleepT:gs(2.5), wakeDmg:60, groggyT:gs(2)','sleep chain');
has('skateCd:gs(9), skateT:gs(1.8), skateMove:2.5, skateTake:.50','skate values');
has('ultDmg:140, ultCd:gs(12), ultWind:gs(1.2)','ultimate values');
has("name:'Conan Edogawa'",'roster entry');
has("tag:'Strategist · Controller · Ranged – Analysis – Precision'",'role');
has("Locked – Gather 4 Clues",'locked text');
has("Case Solved – One Truth Prevails ready",'case solved text');
has('function conanAddClue','clue engine');
has('function conanWatchSkills','active-skill observation');
has('function conanObservedClocks','observation distinguishes active skills from legacy basic attacks');
has("k!=='s1'||o.key==='tanjiro'||o.key==='gojo'||o.key==='conan'",'legacy s1 basic attacks do not count as active skills');
has('function conanSleepDamage','60 damage wake');
has('function conanSkateMiss','skate miss clue');
has('attempted:new Set(),hitBy:new Set()','skateboard tracks attempted and landed enemy attacks');
has('t.conanSkate.hitBy.add(cred)','landed skateboard attacks do not grant false miss clues');
has('function conanSolvedTarget','ultimate target priority');
has("o.conanWeak=CONAN.weakT; o.conanWeakBy=f",'weakness exposed');
has("if(t.key==='conan'&&!t.swapAs&&t.conanSkate) amt*=CONAN.skateTake",'skate defense');
has('weakT:gs(5), weakTake:1.20, weakMiss:.25','weakness values');
has("src&&src.conanWeak>0&&kind!=='dot'&&kind!=='domain'&&kind!=='true'&&chance(CONAN.weakMiss)",'weakness applies a real 25% miss chance');
has("!(f.conanSleep>0)",'sleep pauses ongoing fighter actions');
has("'One Truth Prevails!'",'victory voice line');
has('CONAN EDOGAWA WINS!','victory text');
assert(!/const CONAN=\{[^}]*maxHp/s.test(s),'CONAN must not hard-code Maximum HP');
assert(p.includes("name:'Conan Edogawa'"),'play build contains Conan');
assert(p.includes('function conanAddClue'),'play build contains Conan engine');
console.log('Conan contract: PASS');
